pull_request_rules:
  - name: Automatic merge for gitlocalize-app and dependabot
    conditions:
      - or:
          - author=mtdvlpr
          - author=gitlocalize-app[bot]
          - and:
              - author=dependabot[bot]
              - title~=^Bump [^\s]+ from ([\d]+)\..+ to \1\.
    actions:
      merge:
        method: merge
