pull_request_rules:
  - name: Automatic merge for gitlocalize-app, crowdin and dependabot
    conditions:
      - or:
          - author=mtdvlpr
          - author=gitlocalize-app[bot]
          - and:
              - or:
                  - author=mtdvlpr
                  - author=sircharlo
              - title~=^New Crowdin
          - and:
              - author=dependabot[bot]
              - or:
                 - title~=^Bump [^\s]+ from ([\d]+)\..+ to \1\.
                 - title~=^chore\(deps-dev\). bump [^\s]+ from ([\d]+)\..+ to \1\.
    actions:
      update:
      merge:
        method: merge
