domain: mtdvlpr.github.io # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://mtdvlpr.github.io # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /meeting-media-manager # place folder name if the site is served in a subfolder
github: 'https://github.com/sircharlo/meeting-media-manager'
permalink: '/:title'
title: 'M³ - Meeting Media Manager'
sass:
  style: compressed
defaults:
  - scope:
      path: ''
      type: 'pages'
    values:
      layout: 'default'
  - scope:
      path: 'posts/de/**/*'
    values:
      lang: 'de'
  - scope:
      path: 'posts/en/**/*'
    values:
      lang: 'en'
  - scope:
      path: 'posts/es/**/*'
    values:
      lang: 'es'
  - scope:
      path: 'posts/et/**/*'
    values:
      lang: 'et'
  - scope:
      path: 'posts/fi/**/*'
    values:
      lang: 'fi'
  - scope:
      path: 'posts/fr/**/*'
    values:
      lang: 'fr'
  - scope:
      path: 'posts/it/**/*'
    values:
      lang: 'it'
  - scope:
      path: 'posts/nl/**/*'
    values:
      lang: 'nl'
  - scope:
      path: 'posts/pt/**/*'
    values:
      lang: 'pt-BR'
  - scope:
      path: 'posts/pt-pt/**/*'
    values:
      lang: 'pt-PT'
  - scope:
      path: 'posts/ru/**/*'
    values:
      lang: 'ru'
  - scope:
      path: 'posts/sv/**/*'
    values:
      lang: 'sv'
