name: Build/release

on:
  workflow_dispatch:
  push:
    paths:
      - 'yarn.lock'
      - 'package.json'
      - 'builder.config.js',
      - 'src/main/boot/*.js',
      - '.electron-nuxt/**/*'

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2.3.4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 16
          check-latest: true

      - name: Install dependencies
        run: yarn install

      - name: Build/release Electron app
        env:
          GH_TOKEN: ${{ secrets.github_token }}
        run: yarn run build -p onTag
