name: build/release

on:
  workflow_dispatch:
  pull_request:
    branches: [main, master]
  push:
    paths:
      - 'yarn.lock'
      - 'package.json'
      - 'builder.config.js'
      - 'src/main/**/*'
      - '.electron-nuxt/**/*'
      - 'src/renderer/nuxt.config.js'

jobs:
  lint:
    name: Run linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.0.2

      - name: Setup node
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 16
          check-latest: true

      - name: Install yarn@latest
        run: yarn set version stable

      - name: Install dependencies
        run: yarn install

      - name: Lint code
        run: yarn lint

  build:
    name: Build/release
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.0.2

      - name: Setup node
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 16
          check-latest: true

      - name: Install yarn@latest
        run: yarn set version stable

      - name: Install dependencies
        run: yarn install

      - name: Build/release Electron app
        env:
          GH_TOKEN: ${{ secrets.github_token }}
        run: yarn run build -p onTagOrDraft
