name: Build/release

on:
  workflow_dispatch:
  push:
    paths:
      - 'yarn.lock'
      - 'package.json'
      - 'builder.config.js'
      - 'src/main/**/*'
      - '.electron-nuxt/**/*'
      - 'src/renderer/nuxt.config.js'

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3.0.2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 16
          check-latest: true

      - name: Update Yarn
        run: yarn set version stable

      - name: Install dependencies
        run: yarn install

      - name: Lint code
        run: yarn lint

      - name: Build/release Electron app
        env:
          GH_TOKEN: ${{ secrets.github_token }}
        run: yarn run build -p onTag
